apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlessService.name }}
  labels:
    app.kubernetes.io/name: {{ include "arcadedb-cluster.name" . | default "arcadedb-cluster" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: binary-raft
      port: {{ .Values.service.binaryPort }}
      targetPort: 2424
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 2480
    - name: bolt
      port: {{ .Values.service.boltPort }}
      targetPort: 7687
  selector:
    app.kubernetes.io/name: {{ include "arcadedb-cluster.name" . | default "arcadedb-cluster" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
